### PR TITLE
CurrentLocation

### PR DESCRIPTION
**Pull request by CactusGreen**
Fixed and moved CurrentLocation method to MainWindow form

### CODE REVIEW

**Comment by CactusGreen** [comment]
This should fix the sorting by distance bug. New GetCurrentLocation method can be used, where getting current location was needed, instead of calculating it every time.

**Comment by CactusGreen** [comment]
Seems like some continuous-integration checks failed, it will be interesting to look into it. But that is work for another day.

**Comment by joklek** [comment]
in `BeerOverflowWindowsApp.UnitTests\BeerOverflowWindowsApp.UnitTests.csproj`

add a `<Reference Include="System.Device" />` at line 49-50

**Comment by CactusGreen** [comment]
I added the missing reference but i do not know how to resolve conflicts. Anyone has any ideas?

**Comment by CactusGreen** [comment]
Ok i think it should work properly now

**Comment by joklek** [comment]
Does it seem like a good solution to have "distance to" in the bar class? Then we wouldn't need to calculate it each time when sorting and when displaying the distance. 

If the user moves, the distances would be counted twice, in our current model, and only once in my suggested one. The suggested field would obviously be non serializable. What do you think?

**Comment by CactusGreen** [comment]
That could be a good idea. I'll see how it looks.

**Comment by CactusGreen** [comment]
This is no longer needed. See CurrentLocationFix

**Pull request closed without merging**
