### PR TITLE
Fix: Smarter location filter and other fixes

### PR DESCRIPTION
**Pull request by joklek**
Commits for this request start from cffaed05d4a3260ca9f516a95924d1ad099cb8df, sorry the clusterfcuk.

If you experience crashes on first run, delete `barsData.json` in `*\GitProjectFolder\BeerOverflowWindowsApp\bin\Debug`

## Main stuff

* Test if bars are nearby by using their coordinates (with GeoCoordinates), not some voodoo magic.

* **BarDataModel implements List\<BarData\>** instead of having a variable of it. Didn't see an advantage of it doing so.
 
* Disable button while search is going on + some threading magic for it to work.

* Fix crash if deserializing an empty file.

## Minor stuff

* Import System.Configuration for easier config file import.
 
* Move default radius value to config file.
 
* Fix BarRaters namespace declaration.

* Add screenshot to README.md.

### CODE REVIEW

**Comment by augisjay** [comment]
Hey, I think that there should be a some kind of unit of measurement pointed out in the bar 'Distance', because it's not clear whether there are meters or minutes or something else.

**Comment by augisjay** [comment]
And also, maybe there's a way to sort out bars/pubs out from night clubs, restaurants etc. in a sorting list?

**Comment by CactusGreen** [comment]
I think we could just change column header from Distance to Distance(m.) or something like that.

**Comment by CactusGreen** [comment]
Bar filtering by type is entirely different project and i think no one is working on it yet.

**Comment by augisjay** [comment]
Yes, Distance(m) would be enough for now.

**Pull request merged**
