### PR TITLE
Feature: UI refinement and UnitTest improvement

### PR DESCRIPTION
**Pull request by joklek**
This pull request is built on #30 . Would want to merge after it is merged.

Changelog: 
- Moved the UI components into a grid. This makes UI more responsive.
- Show progress in taskbar (Done with WindowsApiCodePack NuGet package).
- Make a SortList method for the MainWindow. 
- SortList updates Column header sort direction glyph AKA Show sort direction by default.
- Fix comparers, so that they always work as expected. The rule is "(n1 > n2) ? +1 : -1".
- Change UnitTests according to comparer changes.
- Add new UnitTests for ComparerByRatingUnitTests which handle nulls.
- Add one UnitTest for BarRatingUnitTests to test how it handles unexpected arguments.
- A bunch of small renames, hope they're not too annoying.

### CODE REVIEW

**Comment by CactusGreen** [comment]
toolTip.Show(toolTipMessages[lastLocation], this, e.X + 10, e.Y + 10, 3000); throws System.IndexOutOfRangeException once in a while(Pretty sure this is an older issue).
When something changes in dataGridView, Title/rating columns width changes by a few pixels.

**Comment by joklek** [comment]
Never experienced it, will play around and try to reproduce. Any tips on that?

**Comment by CactusGreen** [comment]
I was just randomly clicking table rows and glasses to rate bars.

**Comment by CactusGreen** [comment]
Doesn't look like i can reproduce it either.

**Comment by CactusGreen** [comment]
As far as i understand, it just shows a tooltip, so adding a try catch around it and thinking how nice error logging would be at some point should fix it.

**Comment by CactusGreen** [comment]
Ok i think i know how to reproduce it.
Click a glass, drag it outside form and release.

**Comment by joklek** [comment]
Finally, a first real bug!
Filing a bug report. And you are right, this is an older issue. Was scared a bit.

**Pull request merged**
